/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2025-11-13T17:52:39.602Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Eric Palin",
      photo: "https://app.salesgenius.co/api/user-images/c663e095-4887-4d9a-871f-93f4a6542527?v=c44b72ac62160ed4290f083ad82836145904c53f39c39270579752d91ccc0e95",
      phone: "403-559-6847",
      email: "eric.l.palin@gmail.com",
      company: "RE/MAX House of Real Estate",
      license: "RECO #84397152",
      repo: "New-Listing-532",
      companyAddress: "4034 16 St SW, Calgary, AB T2T 6T8",
      companyLogo: "https://s3.amazonaws.com/realnex.production/Companies/68328/OfficeLogo_cropped.jpg"
    },
    social: {
      instagram: "https://www.instagram.com/ericpalinyyc",
      facebook: "https://www.facebook.com/ericpalinyyc",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: "https://www.linkedin.com/in/ericpalinyyc/"
    },
    email: "eric.l.palin@gmail.com",
    phone: "4035596847",
    address: "4034 16 St SW, Calgary, AB T2T 6T8",
    hours: "Mon-Fri: 9am-5pm",
    mapLocation: {
      lat: 43.7,
      lng: -79.4
    },
    socialLinks: {
      instagram: "https://www.instagram.com/ericpalinyyc",
      facebook: "https://www.facebook.com/ericpalinyyc",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: "https://linkedin.com/company/executivehomesrealtyinc"
    },
    agent2: null
  };

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738054-Tano-1807-16-Web-Res.jpg",
      alt: "Property image 1",
      category: ""
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738776-Tano-1807-13-Web-Res.jpg",
      alt: "Property image 2",
      category: ""
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333739086-Tano-1807-9A-Web-Res.jpg",
      alt: "Property image 3",
      category: ""
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333739795-Tano-1807-14A-Web-Res.jpg",
      alt: "Property image 4",
      category: ""
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333740462-Tano-1807-11B-Web-Res.jpg",
      alt: "Property image 5",
      category: ""
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333740882-Tano-1807-7-Web-Res.jpg",
      alt: "Property image 6",
      category: ""
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333741287-Tano-1807-5-Web-Res.jpg",
      alt: "Property image 7",
      category: ""
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333741817-Tano-1807-22A-Web-Res.jpg",
      alt: "Property image 8",
      category: ""
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333742234-Tano-1807-9B-Web-Res.jpg",
      alt: "Property image 9",
      category: ""
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333742779-Tano-1807-3B-Web-Res.jpg",
      alt: "Property image 10",
      category: ""
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333743164-Tano-1807-3A-Web-Res.jpg",
      alt: "Property image 11",
      category: ""
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333743718-Tano-1807-12B-Web-Res.jpg",
      alt: "Property image 12",
      category: ""
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333744336-Tano-1807-22C-Web-Res.jpg",
      alt: "Property image 13",
      category: ""
    },
    {
      id: 14,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333744767-Tano-1807-17B-Web-Res.jpg",
      alt: "Property image 14",
      category: ""
    },
    {
      id: 15,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333745410-Tano-1807-2A-Web-Res.jpg",
      alt: "Property image 15",
      category: ""
    },
    {
      id: 16,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333745832-Tano-1807-10B-Web-Res.jpg",
      alt: "Property image 16",
      category: ""
    },
    {
      id: 17,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333746347-Tano-1807-17-Web-Res.jpg",
      alt: "Property image 17",
      category: ""
    },
    {
      id: 18,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333746849-Tano-1807-19B-Web-Res.jpg",
      alt: "Property image 18",
      category: ""
    },
    {
      id: 19,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333747259-Tano-1807-20-Web-Res.jpg",
      alt: "Property image 19",
      category: ""
    },
    {
      id: 20,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333747639-Tano-1807-4-Web-Res.jpg",
      alt: "Property image 20",
      category: ""
    },
    {
      id: 21,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333748015-Tano-1807-6B-Web-Res.jpg",
      alt: "Property image 21",
      category: ""
    },
    {
      id: 22,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333748560-Tano-1807-10C-Web-Res.jpg",
      alt: "Property image 22",
      category: ""
    },
    {
      id: 23,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333749095-Tano-1807-24-Web-Res.jpg",
      alt: "Property image 23",
      category: ""
    },
    {
      id: 24,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333749449-Tano-1807-11A-Web-Res.jpg",
      alt: "Property image 24",
      category: ""
    },
    {
      id: 25,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333749953-Tano-1807-24B-Web-Res.jpg",
      alt: "Property image 25",
      category: ""
    },
    {
      id: 26,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333750303-Tano-1807-8-Web-Res.jpg",
      alt: "Property image 26",
      category: ""
    },
    {
      id: 27,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333750833-Tano-1807-1C-Full-Res.jpg",
      alt: "Property image 27",
      category: ""
    },
    {
      id: 28,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333752209-Tano-1807-1-Web-Res.jpg",
      alt: "Property image 28",
      category: ""
    },
    {
      id: 29,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333752609-Tano-1807-6C-Web-Res.jpg",
      alt: "Property image 29",
      category: ""
    },
    {
      id: 30,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333753137-Tano-1807-23-Web-Res.jpg",
      alt: "Property image 30",
      category: ""
    },
    {
      id: 31,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333753582-Tano-1807-10A-Web-Res.jpg",
      alt: "Property image 31",
      category: ""
    },
    {
      id: 32,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333754028-Tano-1807-18B-Web-Res.jpg",
      alt: "Property image 32",
      category: ""
    },
    {
      id: 33,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333754326-Tano-1807-19-Web-Res.jpg",
      alt: "Property image 33",
      category: ""
    },
    {
      id: 34,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333754703-Tano-1807-1B-Full-Res.jpg",
      alt: "Property image 34",
      category: ""
    },
    {
      id: 35,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333756122-Tano-1807-15A-Web-Res.jpg",
      alt: "Property image 35",
      category: ""
    },
    {
      id: 36,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333756522-Tano-1807-2B-Web-Res.jpg",
      alt: "Property image 36",
      category: ""
    },
    {
      id: 37,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333757147-Tano-1807-22B-Web-Res.jpg",
      alt: "Property image 37",
      category: ""
    },
    {
      id: 38,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333757618-Tano-1807-18-Web-Res.jpg",
      alt: "Property image 38",
      category: ""
    },
    {
      id: 39,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333757949-Tano-1807-14B-Web-Res.jpg",
      alt: "Property image 39",
      category: ""
    },
    {
      id: 40,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333758506-Tano-1807-15B-Web-Res.jpg",
      alt: "Property image 40",
      category: ""
    },
    {
      id: 41,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333759026-Tano-1807-6-Web-Res.jpg",
      alt: "Property image 41",
      category: ""
    },
    {
      id: 42,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333759482-Tano-1807-12-Web-Res.jpg",
      alt: "Property image 42",
      category: ""
    },
    {
      id: 43,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333759925-Tano-1807-21-Web-Res.jpg",
      alt: "Property image 43",
      category: ""
    }
  ];

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "2 Bedrooms",
      description: "Light and attention to detail.",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738054-Tano-1807-16-Web-Res.jpg"
    },
    {
      id: "section2",
      title: "2.5 Bathrooms",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738776-Tano-1807-13-Web-Res.jpg"
    },
    {
      id: "section3",
      title: "1682 SqFt",
      description: "Spacious living area with ample room for your lifestyle",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333739086-Tano-1807-9A-Web-Res.jpg"
    },
    {
      id: "section4",
      title: "$$1,524,900",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333739795-Tano-1807-14A-Web-Res.jpg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Beltline",
    city: "Calgary",
    description: "Beltline is Calgary’s energetic downtown neighbourhood, offering an urban lifestyle steps from Stephen Avenue’s shops, restaurants and entertainment. The area combines cultural assets — including the Olympic Plaza / Arts District and proximity to Arts Commons — with landmark attractions like the Calgary Tower and easy access to riverside green spaces such as Prince’s Island Park.",
    highlights: [
      "Steps from Stephen Avenue Walk, a vibrant pedestrian mall with shops, restaurants, and year‑round entertainment",
      "Close to Olympic Plaza & the Arts District, with proximity to Arts Commons and seasonal public events",
      "Nearby access to Prince’s Island Park and other riverfront green spaces for walking and festivals",
      "Surrounded by downtown’s diverse dining scene, from coffee shops to acclaimed restaurants",
      "Outstanding active-transport scores — Walker's Paradise, Excellent Transit and Biker's Paradise"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "Stephen Avenue Walk",
      distance: "",
      category: "shopping",
      iconName: "ShoppingBag"
    },
    {
      id: 2,
      name: "Prince's Island Park",
      distance: "",
      category: "recreation",
      iconName: "Leaf"
    },
    {
      id: 3,
      name: "Bow Valley College",
      distance: "",
      category: "education",
      iconName: "School"
    },
    {
      id: 4,
      name: "Cafe Alchemist Inc",
      distance: "",
      category: "dining",
      iconName: "Coffee"
    },
    {
      id: 5,
      name: "Love Damian",
      distance: "",
      category: "dining",
      iconName: "Utensils"
    },
    {
      id: 6,
      name: "EB Centre Street Station (TD Free Fare Zone)",
      distance: "",
      category: "transportation",
      iconName: "Car"
    },
    {
      id: 7,
      name: "Eau Claire Park",
      distance: "",
      category: "recreation",
      iconName: "Users"
    },
    {
      id: 8,
      name: "Arts Commons",
      distance: "",
      category: "business",
      iconName: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "98/100",
      caption: "Walker's Paradise",
      iconName: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "86/100",
      caption: "Excellent Transit",
      iconName: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "91/100",
      caption: "Biker's Paradise",
      iconName: "Compass",
      color: "bg-blue-500"
    }
  ];

// openHouseBenefits configuration
export const openHouseBenefits = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 2 bedroom, 2.5 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Condo Apartment sales in Calgary.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "N/A",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    nextDate: "Sunday, November 16, 2025",
    time: "3:00 PM - 6:00 PM",
    host: "Eric Palin",
    phone: "4035596847",
    email: "eric.l.palin@gmail.com",
    ctaText: "RSVP for Open House",
    virtualTourAvailable: false,
    virtualTourUrl: "",
    allOpenHouses: [
      {
        date: "Sunday, November 16, 2025",
        time: "3:00 PM - 6:00 PM"
      },
      {
        date: "Sunday, November 16, 2025",
        time: "3:00 PM - 6:00 PM"
      },
      {
        date: "Sunday, November 16, 2025",
        time: "3:00 PM - 6:00 PM"
      }
    ],
    date: "Sunday, November 16, 2025",
    startTime: "3:00 PM",
    endTime: "6:00 PM",
    location: "1807, 108 9 Ave SW",
    registerLink: "#package"
  };

// packageItems configuration
export const packageItems = [
    {
      id: 1,
      title: "Detailed Floor Plans",
      description: "Complete architectural layouts showing the 2 bedroom, 2.5 bathroom configuration with precise measurements.",
      iconName: "FileText"
    },
    {
      id: 2,
      title: "Recent Neighborhood Sales",
      description: "Comparative market analysis of recent Condo Apartment sales in Calgary.",
      iconName: "BarChart2"
    },
    {
      id: 3,
      title: "School District Information",
      description: "N/A",
      iconName: "GraduationCap"
    },
    {
      id: 4,
      title: "Property Inspection Report",
      description: "Professional assessment highlighting recent upgrades and maintenance history.",
      iconName: "CheckSquare"
    },
    {
      id: 5,
      title: "Financing Options Guide",
      description: "Current mortgage rates and financing programs available for this price range.",
      iconName: "DollarSign"
    },
    {
      id: 6,
      title: "Neighborhood Amenities Map",
      description: "Interactive guide to nearby amenities and transportation options.",
      iconName: "Map"
    }
  ];

// property configuration
export const property = {
    name: "1807, 108 9 Ave SW",
    address: {
      street: "1807, 108 9 Ave SW",
      city: "Calgary",
      state: "AB",
      zip: "T2P 0T1",
      country: "Canada"
    },
    price: "$1,524,900",
    beds: 2,
    baths: 2.5,
    sqft: 1682,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    type: "Condo Apartment",
    status: "For Sale",
    description: "A renowned Canadian luxury brand and its residential concept being completely transformed through a flawless renovation into a modern luxury. ",
    shortDescription: "2 BEDS + 2.5 BATHS in Calgary",
    longDescription: "- Professionally Reimagined and completely renovated by recognized design firm Tano Studio. - South western exposure/views - Opulent finishes and the most prestigious amenities.  - The most detailed and attentive concierge in the industry. ",
    mainFeatures: [],
    propertyType: "Condo Apartment",
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738054-Tano-1807-16-Web-Res.jpg",
    heroCaption: "Southwest Views + Concierge + Opulent Finishes = Your Perfect Luxury Condo Just Listed!"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    "Behind the main door, there’s a private locker. This locker is a standout feature, providing a secure space for deliveries and a designated area for hanging dry cleaning! receive packages securely inside your abode or leave and retrieve dry cleaning.",
    "This is an exclusive hotel style residence. Offering all the conveniences and amenities of the Luxury Hotel Les Germaine. At the touch of a button, from room service-events, spas - dining."
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "https://s3.amazonaws.com/realnex.production/Companies/68328/OfficeLogo_cropped.jpg",
    logoAlt: "1807, 108 9 Ave SW",
    favicon: "/favicon.ico",
    colors: {
      primary: "#D9A566",
      primaryDark: "#8B6839",
      primaryLight: "#E6C38C",
      dark: "#111111",
      light: "#FFFFFF"
    },
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738054-Tano-1807-16-Web-Res.jpg",
    footer: {
      copyrightText: "© 2024 1807, 108 9 Ave SW. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change."
    },
    companyName: "RE/MAX House of Real Estate",
    companyLogo: "https://s3.amazonaws.com/realnex.production/Companies/68328/OfficeLogo_cropped.jpg",
    accentColor: "#D9A566",
    footerText: "© 2024 1807, 108 9 Ave SW. All rights reserved."
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "1807, 108 9 Ave SW | Condo Apartment | Calgary",
    description: "Southwest Views + Concierge + Opulent Finishes = Your Perfect Luxury Condo Just Listed!",
    keywords: "condo apartment, Calgary real estate, 2 bedroom, 2.5 bathroom, $1,524,900",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1761333738054-Tano-1807-16-Web-Res.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://1807,1089avesw.com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Eric Palin provided exceptional service and found us exactly what we were looking for in Calgary.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Eric Palin presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Eric Palin knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg"
    }
  ];

